version: "3.9"  # optional since v1.27.0

services:
  nginx:
    build: ./requirements/nginx/.
    networks:
      - net
    ports:
      - "443:443"
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress/.
    networks:
      - net
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb/.
    volumes:
      - wordpress_table:/usr/local/mariadb
    networks:
      - net

volumes:
  wordpress_php:
  wordpress_table:

networks:
  net:
    driver: bridge
