version: "3.9"  # optional since v1.27.0

services:
  nginx:
    build: ./requirements/nginx/.
    image: nginx:1.0
    container_name: nginx
    volumes:
      - wordpress_php:/var/www/html
    networks:
      - net
    ports:
      - "443:443"
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD-SHELL", "ping -w 2 wordpress || kill 1"]
      interval: 1s
      timeout: 10s
      retries: 1
    restart:  always
  
  wordpress:
    build: ./requirements/wordpress/.
    image: wordpress:1.0
    container_name: wordpress
    environment:
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASS: ${WORDPRESS_DB_PASS}
      WP_GOD:  ${WP_GOD}
      WP_GOD_PASS:  ${WP_GOD_PASS}
      WP_GOD_EMAIL: ${WP_GOD_EMAIL}
      WP_USR1: ${WP_USR1}
      WP_USR1_PASS: ${WP_USR1_PASS}
      WP_USR1_EMAIL: ${WP_USR1_EMAIL}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
    volumes:
      - wordpress_php:/var/www/html
    networks:
      - net
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD-SHELL", "ping -w 2 mariadb || kill 1"]
      interval: 1s
      timeout: 10s
      retries: 1
    restart: always
  
  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb:1.0
    container_name: mariadb
    environment:
      ROOT_PASS: ${ROOT_PASS}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASS: ${WORDPRESS_DB_PASS}
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - net
    restart: always

volumes:
  wordpress_php:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/inskim/data/wordpress_php'
  wordpress_db:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/inskim/data/wordpress_db'

networks:
  net:
    driver: bridge
