version: "3.9"  # optional since v1.27.0

services:
  nginx:
    build: ./requirements/nginx/.
    image: nginx:inception
    container_name: nginx
    volumes:
      - wordpress_php:/usr/share/webapps
    networks:
      - net
    ports:
      - "443:443"
    depends_on:
      - wordpress
    #restart:  always
  
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    environment:
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASS: ${WORDPRESS_DB_PASS}
      WORDPRESS_GOD:  ${WORDPRESS_GOD}
      WORDPRESS_GOD_PASS:  ${WORDPRESS_GOD_PASS}
      WORDPRESS_USER1: ${WORDPRESS_USER1}
      WORDPRESS_USER1_PASS: ${WORDPRESS_USER1_PASS}
    volumes:
      - wordpress_php:/usr/share/webapps
    networks:
      - net
    depends_on:
      - mariadb
    #restart: always
  
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    environment:
      ROOT_PASS: ${ROOT_PASS}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASS: ${WORDPRESS_DB_PASS}
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - net
    #restart: always

volumes:
  wordpress_php:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/Users/insub/data'
  wordpress_db:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/Users/insub/data'

networks:
  net:
    driver: bridge
