version: "3.9"  # optional since v1.27.0

services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    environment: 
      hi: ${hi}
    volumes:
      - wordpress_php:/usr/share/webapps/wordpress
    networks:
      - net
    ports:
      - "443:443"
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    volumes:
      - wordpress_php:/usr/share/webapps/wordpress
    networks:
      - net
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - wordpress_db:/root
    networks:
      - net

volumes:
  wordpress_php:
  wordpress_db:

networks:
  net:
    driver: bridge
