version: "3.9"  # optional since v1.27.0

services:
  web:
    build: ./requirements/nginx/.
    ports:
      - "80:80"
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    hostname: wordpress
    build: ./requirements/wordpress/.
    ports:
      - "9000:9000"
